version: '2'
services:
  zookeeper:
    image: hyperledger/fabric-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka0:
    image: hyperledger/fabric-kafka
    container_name: kafka0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka0
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=0
      - KAFKA_LISTENERS=EXTERNAL://kafka0:9092,REPLICATION://kafka0:9093
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL://kafka0:9092,REPLICATION://kafka0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,REPLICATION:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=REPLICATION
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99*1024*1024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_NUM_REPLICA_FETCHERS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
